/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrBuscarProductos;
import dao.BasicDao;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.FrmServicioHabitacion;
import vista.StandardForm;

/**
 *
 * @author ChristianHC
 */
public class FrmBuscarProducto extends StandardForm {

    /**
     * Creates new form FrmBuscarProducto
     */
    CtrBuscarProductos mCtrBuscarProductos;
    FrmServicioHabitacion servHab;
    public double montoAcumulado = 0;
    
    public FrmBuscarProducto(){
       initComponents(); 
    }
    public FrmBuscarProducto(FrmServicioHabitacion mServHab) {
        initComponents();
        this.servHab = mServHab;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcati = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaProd = new javax.swing.JTable();
        btnAgregarProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtTermProd1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 145, 15));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Buscar Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setText("Nombre Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        getContentPane().add(txtcati, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, -1));

        tablaListaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaListaProd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 440, 130));

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 100, 30));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, 30));

        jLabel3.setText("Categoria:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 450, 10));
        getContentPane().add(txtTermProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        
        
        
        DefaultTableModel modelo = (DefaultTableModel) FrmServicioHabitacion.tablaProductos.getModel();
        DefaultTableModel modeloInterno = (DefaultTableModel) tablaListaProd.getModel();
        modelo.addRow(new Object[]{
            servHab.txtDNI.getText(),
            servHab.txtFullName.getText(),
            servHab.txtHabitacion.getText(),
            servHab.txtFechaActual.getText(),
            modeloInterno.getValueAt(tablaListaProd.getSelectedRow(), 1),
            txtCantidad.getText(),
            modeloInterno.getValueAt(tablaListaProd.getSelectedRow(), 2),
            ""+(
                    Integer.parseInt(txtCantidad.getText()) * Double.parseDouble(modeloInterno.getValueAt(tablaListaProd.getSelectedRow(), 2).toString())
               )
        });
        montoAcumulado += Integer.parseInt(txtCantidad.getText()) * Double.parseDouble(modeloInterno.getValueAt(tablaListaProd.getSelectedRow(), 2).toString());
        this.servHab.MontoAcumuladoTotal += montoAcumulado;
        this.servHab.txtTotalPagar.setText(""+this.servHab.MontoAcumuladoTotal);
        //this.servHab.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // BOTON CANCELAR
        JOptionPane.showMessageDialog(null,"No escogio Ningun Producto");
       this.setVisible(false);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    void buscar(){
        
           DefaultTableModel modelo = (DefaultTableModel) tablaListaProd.getModel();
           if(txtTermProd1.getText()!=null && txtcati.getText()!=null){
            try{
            ArrayList<Map<String,String>> resultadoProductos = BasicDao.select("Producto", new String[]{"*"}, "NombrePro like '%"+txtTermProd1.getText().toString()+"%'"); 
            
            for(int i = 0; i<resultadoProductos.size() ; i++){
                Object datos[]=new Object[3];
                Map<String,String> Producto = resultadoProductos.get(i);
                modelo.addRow(new Object[]{
                    Producto.get("idProducto"),
                    Producto.get("NombrePro"),
                    Producto.get("PrecioPro")
                });
            }  
             }catch(Exception e){
                 ArrayList<Map<String,String>> resultadoProductos = BasicDao.select("Producto", new String[]{"*"}, "NombrePro like '%"+txtcati.getText().toString()+"%'"); 
            
            for(int i = 0; i<resultadoProductos.size() ; i++){
                Object datos[]=new Object[3];
                Map<String,String> Producto = resultadoProductos.get(i);
                modelo.addRow(new Object[]{
                    Producto.get("idProducto"),
                    Producto.get("NombrePro"),
                    Producto.get("PrecioPro")
                });
            } 
             }
            }else{
               JOptionPane.showMessageDialog(null, "Producto no Encontrado");
           }
              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BasicDao.init();
                BasicDao.DEBUG=true;
                FrmBuscarProducto mBuscarProductos = new FrmBuscarProducto();
                mBuscarProductos.show();
                mBuscarProductos.createController();
                mBuscarProductos.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tablaListaProd;
    private javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtTermProd1;
    public javax.swing.JTextField txtcati;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public Object getViewController() {
        return mCtrBuscarProductos;
    }

    @Override
    public void createController() {
        mCtrBuscarProductos = new CtrBuscarProductos(this);
        mCtrBuscarProductos.loadData();
    }
    
}
