/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.BasicDao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.StandardForm;
import vista.StandardForm;

/**
 *
 * @author ChristianHC
 */
public class FrmServicioHabitacion extends StandardForm {

    /**
     * Creates new form FrmServicioHabitacion
     */
    
    //public static DefaultTableModel tbmodel = (DefaultTableModel) FrmServicioHabitacion.tablaProductos.getModel();
    
    public double MontoAcumuladoTotal = 0;
    int idAlojamiento = 0;
    int idHuesped = 0;
    int idHabitacion = 0;
    
    public FrmServicioHabitacion() {
        initComponents();
        txtFechaActual.setText(FechaActual());
        txtTotalPagar.setText(""+MontoAcumuladoTotal);
    }
    
    public static String FechaActual(){
        Date fecha=new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY hh:mm:ss a");
        return formatoFecha.format(fecha);
    }
    
    public void bloquear(){
        txtFullName.setEnabled(false);
        txtHabitacion.setEnabled(false);
        txtTotalPagar.setEnabled(false);
        btnBuscarProductos.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnEliminarFila.setEnabled(false);
    }
    
    public void desbloquear(){
        txtFullName.setEnabled(true);
        txtHabitacion.setEnabled(true);
        txtTotalPagar.setEnabled(true);
        btnBuscarProductos.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnEliminarFila.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        btnBuscarProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnConsultarDNI = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtHabitacion = new javax.swing.JTextField();
        btnEliminarFila = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarProductos.setText("Buscar Producto");
        btnBuscarProductos.setEnabled(false);
        btnBuscarProductos.setName("btnBuscarProductos"); // NOI18N
        btnBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombres y Apellidos", "Habitacion", "Fecha", "Producto", "Precio", "Cantidad", "Total"
            }
        ));
        tablaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 560, 100));

        jLabel2.setText("Total a pagar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        txtTotalPagar.setEnabled(false);
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 100, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 100, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 90, -1));

        jLabel3.setText("Detalle Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtFechaActual.setText("dd/MM/YYYY");
        getContentPane().add(txtFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Servicios a la Habitación");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 10));

        jLabel4.setText("DNI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 170, -1));

        btnConsultarDNI.setText("Consultar");
        btnConsultarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDNIActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 640, 10));

        jLabel5.setText("Nombres y Apellidos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setText("N° Habitación");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        txtFullName.setEnabled(false);
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, -1));

        txtHabitacion.setEnabled(false);
        getContentPane().add(txtHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, -1));

        btnEliminarFila.setText("Eliminar");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 630, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductosActionPerformed
        FrmBuscarProducto buscar = new FrmBuscarProducto(this);
        buscar.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnBuscarProductosActionPerformed

    private void btnConsultarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDNIActionPerformed
        Map<String,String> huespedes=null;
       //Consultar Huesped
        if(txtDNI.getText().length()>0 && txtDNI.getText().length()==8){
            try{
           
                ArrayList<Map<String,String>> resultaHuespedes=BasicDao.select("Huesped", new String[]{"*"}, "DNIHue="+this.txtDNI.getText());
                huespedes=resultaHuespedes.get(0);//objeto huesped
                this.txtFullName.setText(huespedes.get("NombreHue"));
                idHuesped = Integer.parseInt(huespedes.get("idHSP"));
                
                desbloquear();
                } catch(Exception e){
                   JOptionPane.showMessageDialog(null,"Huesped no se encuentra alojado en estos momentos");
                   bloquear();
                   txtFullName.setText("");
                   txtHabitacion.setText("");
               }


                ArrayList<Map<String,String>> resultaHabitaciones=BasicDao.select(new String[]{"Habitacion","DetalleReserva"}, new String[]{"*"}, new String[]{"Habitacion_idHab","idHab"},"Huesped_idHSP="+huespedes.get("idHSP"));
                Map<String,String> habitaciones=resultaHabitaciones.get(0);
                txtHabitacion.setText(habitaciones.get("NumeroHab"));
                ArrayList<Map<String,String>> resultAlojamiento = BasicDao.select("Alojamiento", new String[]{"*"},"Reserva_idReserva="+habitaciones.get("Reserva_idReserva").toString());
                idAlojamiento = Integer.parseInt(resultAlojamiento.get(0).get("idAlojamiento"));
                
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese un DNI correcto");
                   bloquear();
                   txtFullName.setText("");
                   txtHabitacion.setText("");
        }
       
    }//GEN-LAST:event_btnConsultarDNIActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       JOptionPane.showMessageDialog(null,"Salir de Servicio a la Habitación");
       this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        /*
        DefaultTableModel modelo = (DefaultTableModel) tblServiciosExtras.getModel();
        
        precioAcumulado -= Integer.parseInt(modelo.getValueAt(tblServiciosExtras.getSelectedRow(), 5).toString());
        txtpago2.setText(""+precioAcumulado);
        modelo.removeRow(tblServiciosExtras.getSelectedRow());
        */
        
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        MontoAcumuladoTotal -= Double.parseDouble(modelo.getValueAt(tablaProductos.getSelectedRow(), 7).toString());
        txtTotalPagar.setText(""+MontoAcumuladoTotal);
        modelo.removeRow(tablaProductos.getSelectedRow());
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        try {
            
            if(tablaProductos.getRowCount()>0){
                
                DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
                
                String tabla1 = "PedidoHabitacion";
                    
                String items1[]      = new String[4];
                String valores1[]    = new String[4];

                items1[0] = "Alojamiento_idAlojamiento";
                items1[1] = "FechaPHa";
                items1[2] = "TotalPHa";
                items1[3] = "Huesped_idHSP";


                String fecha = txtFechaActual.getText();
                String fechaCambiada = fecha.replace("/","-");
                SimpleDateFormat formatFecha = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                Date fechaFormateada = formatFecha.parse(fechaCambiada);
                SimpleDateFormat formatoFecha2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                valores1[0] = ""+this.idAlojamiento;
                valores1[1] = ""+formatoFecha2.format(fechaFormateada);
                valores1[2] = ""+Double.parseDouble(String.valueOf(MontoAcumuladoTotal));
                valores1[3] = ""+idHuesped;
                
                
                BasicDao.insert(tabla1, items1, valores1);
                Map<String,String> ultRegistroPedidoHabitacion = BasicDao.selectLastRow(tabla1,new String[]{"IdPerdidoHabitacion"}, "IdPerdidoHabitacion");

                String tabla2 = "PedidoHabitacion";

                String items2[]      = new String[6];
                String valores2[]    = new String[6];

                items2[0] = "PrecioUnitarioDPe";
                items2[1] = "CantidadDPe";
                items2[2] = "SubTotalDPe";
                items2[3] = "Producto_idProducto";
                items2[4] = "PedidoHabitacion_IdPerdidoHabitacion";
                items2[5] = "PedidoHabitacion_Alojamiento_idAlojamiento";
                    
                for(int i = 0; i<tablaProductos.getRowCount();i++){
                    
                    ArrayList<Map<String,String>> ProductosList = BasicDao.select("Producto", new String[]{"idProducto","PrecioPro"}, "NombrePro = '"+
                            modelo.getValueAt(i,4).toString()
                            +"'");
                    
                    valores2[0] = ""+ProductosList.get(0).get("PrecioPro");
                    valores2[1] = ""+modelo.getValueAt(i, 6);
                    valores2[2] = ""+modelo.getValueAt(i, 7);
                    valores2[3] = ""+ProductosList.get(0).get("idProducto");
                    valores2[4] = ""+ultRegistroPedidoHabitacion.get("IdPerdidoHabitacion");
                    valores2[5] = ""+idAlojamiento;
                    System.out.println(valores2);
                    //BasicDao.insert(tabla2, items2, valores2);
                    
                }
                JOptionPane.showMessageDialog(null, "Registro sastifactorio");
                while(modelo.getRowCount()>0)modelo.removeRow(0);
                MontoAcumuladoTotal = 0;
                txtTotalPagar.setText(""+MontoAcumuladoTotal);
            }else{
                JOptionPane.showMessageDialog(null, "Debe ingresar al menos 1 servicio extra para guardar.");
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.getMessage();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServicioHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServicioHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServicioHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServicioHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BasicDao.init();
                final FrmServicioHabitacion mServicioHabitacion = new FrmServicioHabitacion();
                mServicioHabitacion.createController();
                mServicioHabitacion.show();
                mServicioHabitacion.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnConsultarDNI;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTable tablaProductos;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JLabel txtFechaActual;
    public javax.swing.JTextField txtFullName;
    public javax.swing.JTextField txtHabitacion;
    public javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getViewController() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
